name: Python-CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask pytest

      - name: Run tests
        run: |
          pytest test_app.py

  approve-deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://heroku/ayush.com
    steps:
      - name: Wait for manual approval
        run: echo "✅ Tests Passed. Ready for deployment."

